
services:
  fact-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: fact_api
  #   ports:
  #     - "5432:5432"
